### ISSUE TITLE
About shrink function

### ISSUE THREAD

**Issue by xuyaojian123** [daniel03c1/BNeRF#11]
Thank you very much for your work, I'd love to understand your code ideas!

This is `original TensorRF shrink function`

![image](https://github.com/daniel03c1/masked_wavelet_nerf/assets/51220835/eda11c79-44b3-44df-a63a-d27bd58595af)

This your `modified shrink function`

![image](https://github.com/daniel03c1/masked_wavelet_nerf/assets/51220835/e148e09a-bbc6-4f54-9b7f-d8fe8a734d21)

What is the function of `shrink`? What is the difference from the `original TensoRF shrink function`? I see you used the F.grid_sample method, but the original TensoRF shrink function did not. In addition, what is the function of the variable `unit`, especially why `self.init_mask()` function is needed at the end? Maybe I have a lot of questions,but I hope to get your reply, thank you!

**Comment by daniel03c1** [comment]
I really appreciate your interest in our work.
As you pointed out, the only difference is "unit" and mask initialization.
"Unit" ensures that the height and width of planes are divisible by the chosen "unit". This choice is deliberate, as it ensures that both the original plane and the result of applying the inverse discrete wavelet transform (idwt) to the plane maintain the same dimensions, assuming wavelets downscale planes by exactly two. If you want to use a much higher level of multilevel wavelet transformation, you might need to increase the unit size.
Mask initialization is just a function that updates masks since planes have been shrunk.

**Comment by xuyaojian123** [comment]
> I really appreciate your interest in our work. As you pointed out, the only difference is "unit" and mask initialization. "Unit" ensures that the height and width of planes are divisible by the chosen "unit". This choice is deliberate, as it ensures that both the original plane and the result of applying the inverse discrete wavelet transform (idwt) to the plane maintain the same dimensions, assuming wavelets downscale planes by exactly two. If you want to use a much higher level of multilevel wavelet transformation, you might need to increase the unit size. Mask initialization is just a function that updates masks since planes have been shrunk.

Thank you!
